### ISSUE TITLE
DarkFilePaneUIBridge: java.lang.IllegalArgumentException: adding container's parent to itself

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#196]
**Describe the bug**

**To Reproduce**

Using latest nightly build from JMeter
Menu Tools > Generate HTML Report
Click on browser, go up to root and try navigating to a folder located inside Downloads folder double clicking on folder name
It looks action is taken as a try to rename folder and fails

Stacktrace:

````
2020-07-25 15:07:10,535 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalArgumentException: adding container's parent to itself
	at java.awt.Container.checkAddToSelf(Container.java:481) ~[?:1.8.0_201]
	at java.awt.Container.addImpl(Container.java:1092) ~[?:1.8.0_201]
	at java.awt.Container.add(Container.java:419) ~[?:1.8.0_201]
	at com.github.weisj.darklaf.ui.table.renderer.IconWrapper.init(IconWrapper.java:54) ~[darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.table.renderer.DarkTableCellEditorDelegate.applyRendererIcon(DarkTableCellEditorDelegate.java:155) ~[darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.table.renderer.DarkTableCellEditorDelegate.prepareEditor(DarkTableCellEditorDelegate.java:121) ~[darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.table.DarkTableUI.getCellEditorComponent(DarkTableUI.java:445) ~[darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.table.DarkTableUI.paintCell(DarkTableUI.java:418) ~[darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.table.DarkTableUIBridge.paintCells(DarkTableUIBridge.java:218) ~[darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.table.DarkTableUIBridge.paint(DarkTableUIBridge.java:145) ~[darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.table.DarkTableUI.paint(DarkTableUI.java:359) ~[darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintComponent(JComponent.java:780) ~[?:1.8.0_201]
	at javax.swing.JComponent.paint(JComponent.java:1056) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[?:1.8.0_201]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[?:1.8.0_201]
	at javax.swing.JViewport.paint(JViewport.java:728) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[?:1.8.0_201]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[?:1.8.0_201]
	at javax.swing.JComponent.paint(JComponent.java:1065) ~[?:1.8.0_201]
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272) ~[?:1.8.0_201]
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732) ~[?:1.8.0_201]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.awt.Dialog.show(Dialog.java:1084) [?:1.8.0_201]
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869) [?:1.8.0_201]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666) [?:1.8.0_201]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePaneUIBridge$DetailsTableModel.setValueAt(DarkFilePaneUIBridge.java:1242) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.JTable.setValueAt(JTable.java:2744) [?:1.8.0_201]
	at javax.swing.JTable.editingStopped(JTable.java:4729) [?:1.8.0_201]
	at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141) [?:1.8.0_201]
	at javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:368) [?:1.8.0_201]
	at javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:233) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.table.renderer.DarkTableCellEditor.stopCellEditing(DarkTableCellEditor.java:181) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.JTable.columnMarginChanged(JTable.java:4598) [?:1.8.0_201]
	at javax.swing.table.DefaultTableColumnModel.fireColumnMarginChanged(DefaultTableColumnModel.java:628) [?:1.8.0_201]
	at javax.swing.table.DefaultTableColumnModel.propertyChange(DefaultTableColumnModel.java:691) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327) [?:1.8.0_201]
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263) [?:1.8.0_201]
	at javax.swing.table.TableColumn.firePropertyChange(TableColumn.java:278) [?:1.8.0_201]
	at javax.swing.table.TableColumn.firePropertyChange(TableColumn.java:284) [?:1.8.0_201]
	at javax.swing.table.TableColumn.setWidth(TableColumn.java:514) [?:1.8.0_201]
	at javax.swing.JTable$2.setSizeAt(JTable.java:3235) [?:1.8.0_201]
	at javax.swing.JTable$5.setSizeAt(JTable.java:3325) [?:1.8.0_201]
	at javax.swing.JTable.adjustSizes(JTable.java:3361) [?:1.8.0_201]
	at javax.swing.JTable.adjustSizes(JTable.java:3329) [?:1.8.0_201]
	at javax.swing.JTable.setWidthsFromPreferredWidths(JTable.java:3243) [?:1.8.0_201]
	at javax.swing.JTable.doLayout(JTable.java:3131) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1698) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) [?:1.8.0_201]
	at java.awt.Container.validate(Container.java:1633) [?:1.8.0_201]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711) [?:1.8.0_201]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708) [?:1.8.0_201]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731) [?:1.8.0_201]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.awt.Dialog.show(Dialog.java:1084) [?:1.8.0_201]
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869) [?:1.8.0_201]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666) [?:1.8.0_201]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePaneUIBridge$DetailsTableModel.setValueAt(DarkFilePaneUIBridge.java:1242) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.JTable.setValueAt(JTable.java:2744) [?:1.8.0_201]
	at javax.swing.JTable.editingStopped(JTable.java:4729) [?:1.8.0_201]
	at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141) [?:1.8.0_201]
	at javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:368) [?:1.8.0_201]
	at javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:233) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.table.renderer.DarkTableCellEditor.stopCellEditing(DarkTableCellEditor.java:181) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.JTable.columnMarginChanged(JTable.java:4598) [?:1.8.0_201]
	at javax.swing.table.DefaultTableColumnModel.fireColumnMarginChanged(DefaultTableColumnModel.java:628) [?:1.8.0_201]
	at javax.swing.table.DefaultTableColumnModel.propertyChange(DefaultTableColumnModel.java:691) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327) [?:1.8.0_201]
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263) [?:1.8.0_201]
	at javax.swing.table.TableColumn.firePropertyChange(TableColumn.java:278) [?:1.8.0_201]
	at javax.swing.table.TableColumn.firePropertyChange(TableColumn.java:284) [?:1.8.0_201]
	at javax.swing.table.TableColumn.setWidth(TableColumn.java:514) [?:1.8.0_201]
	at javax.swing.JTable$2.setSizeAt(JTable.java:3235) [?:1.8.0_201]
	at javax.swing.JTable$5.setSizeAt(JTable.java:3325) [?:1.8.0_201]
	at javax.swing.JTable.adjustSizes(JTable.java:3361) [?:1.8.0_201]
	at javax.swing.JTable.adjustSizes(JTable.java:3329) [?:1.8.0_201]
	at javax.swing.JTable.setWidthsFromPreferredWidths(JTable.java:3243) [?:1.8.0_201]
	at javax.swing.JTable.doLayout(JTable.java:3131) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1698) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) [?:1.8.0_201]
	at java.awt.Container.validate(Container.java:1633) [?:1.8.0_201]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711) [?:1.8.0_201]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708) [?:1.8.0_201]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731) [?:1.8.0_201]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.awt.Dialog.show(Dialog.java:1084) [?:1.8.0_201]
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869) [?:1.8.0_201]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666) [?:1.8.0_201]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePaneUIBridge$DetailsTableModel.setValueAt(DarkFilePaneUIBridge.java:1242) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.JTable.setValueAt(JTable.java:2744) [?:1.8.0_201]
	at javax.swing.JTable.editingStopped(JTable.java:4729) [?:1.8.0_201]
	at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141) [?:1.8.0_201]
	at javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:368) [?:1.8.0_201]
	at javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:233) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.table.renderer.DarkTableCellEditor.stopCellEditing(DarkTableCellEditor.java:181) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.JTable.columnMarginChanged(JTable.java:4598) [?:1.8.0_201]
	at javax.swing.table.DefaultTableColumnModel.fireColumnMarginChanged(DefaultTableColumnModel.java:628) [?:1.8.0_201]
	at javax.swing.table.DefaultTableColumnModel.propertyChange(DefaultTableColumnModel.java:691) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327) [?:1.8.0_201]
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263) [?:1.8.0_201]
	at javax.swing.table.TableColumn.firePropertyChange(TableColumn.java:278) [?:1.8.0_201]
	at javax.swing.table.TableColumn.firePropertyChange(TableColumn.java:284) [?:1.8.0_201]
	at javax.swing.table.TableColumn.setWidth(TableColumn.java:514) [?:1.8.0_201]
	at javax.swing.JTable$2.setSizeAt(JTable.java:3235) [?:1.8.0_201]
	at javax.swing.JTable$5.setSizeAt(JTable.java:3325) [?:1.8.0_201]
	at javax.swing.JTable.adjustSizes(JTable.java:3361) [?:1.8.0_201]
	at javax.swing.JTable.adjustSizes(JTable.java:3329) [?:1.8.0_201]
	at javax.swing.JTable.setWidthsFromPreferredWidths(JTable.java:3243) [?:1.8.0_201]
	at javax.swing.JTable.doLayout(JTable.java:3131) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1698) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) [?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) [?:1.8.0_201]
	at java.awt.Container.validate(Container.java:1633) [?:1.8.0_201]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711) [?:1.8.0_201]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708) [?:1.8.0_201]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731) [?:1.8.0_201]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.awt.Dialog.show(Dialog.java:1084) [?:1.8.0_201]
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869) [?:1.8.0_201]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666) [?:1.8.0_201]
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePaneUIBridge$DetailsTableModel.setValueAt(DarkFilePaneUIBridge.java:1242) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.JTable.setValueAt(JTable.java:2744) [?:1.8.0_201]
	at javax.swing.JTable.editingStopped(JTable.java:4729) [?:1.8.0_201]
	at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141) [?:1.8.0_201]
	at javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:368) [?:1.8.0_201]
	at javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:233) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.table.renderer.DarkTableCellEditor.stopCellEditing(DarkTableCellEditor.java:181) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.JTable.columnMarginChanged(JTable.java:4598) [?:1.8.0_201]
	at javax.swing.table.DefaultTableColumnModel.fireColumnMarginChanged(DefaultTableColumnModel.java:628) [?:1.8.0_201]
	at javax.swing.table.DefaultTableColumnModel.setColumnMargin(DefaultTableColumnModel.java:225) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePaneUIBridge.updateDetailsColumnModel(DarkFilePaneUIBridge.java:626) [darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePane$3.tableChanged(DarkFilePane.java:164) [darklaf-core-2.4.1.jar:2.4.1]
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296) [?:1.8.0_201]
	at javax.swing.table.AbstractTableModel.fireTableStructureChanged(AbstractTableModel.java:216) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePaneUIBridge$DetailsTableModel.updateColumnInfo(DarkFilePaneUIBridge.java:1176) [darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePaneUIBridge.doDirectoryChanged(DarkFilePaneUIBridge.java:871) [darklaf-core-2.4.1.jar:2.4.1]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePaneUIBridge.propertyChange(DarkFilePaneUIBridge.java:931) [darklaf-core-2.4.1.jar:2.4.1]
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327) [?:1.8.0_201]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263) [?:1.8.0_201]
	at java.awt.Component.firePropertyChange(Component.java:8434) [?:1.8.0_201]
	at javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:598) [?:1.8.0_201]
	at javax.swing.plaf.basic.BasicFileChooserUI.changeDirectory(BasicFileChooserUI.java:1171) [?:1.8.0_201]
	at javax.swing.plaf.basic.BasicFileChooserUI.access$000(BasicFileChooserUI.java:50) [?:1.8.0_201]
	at javax.swing.plaf.basic.BasicFileChooserUI$Handler.mouseClicked(BasicFileChooserUI.java:475) [?:1.8.0_201]
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePane$DarkHandler.mouseClicked(DarkFilePane.java:466) [darklaf-core-2.4.1.jar:2.4.1]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270) [?:1.8.0_201]
	at java.awt.Component.processMouseEvent(Component.java:6542) [?:1.8.0_201]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_201]
	at java.awt.Component.processEvent(Component.java:6304) [?:1.8.0_201]
	at java.awt.Container.processEvent(Container.java:2239) [?:1.8.0_201]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_201]
	at java.awt.Container.dispatchEventImpl(Container.java:2297) [?:1.8.0_201]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_201]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) [?:1.8.0_201]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544) [?:1.8.0_201]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) [?:1.8.0_201]
	at java.awt.Container.dispatchEventImpl(Container.java:2283) [?:1.8.0_201]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_201]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) [?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) [?:1.8.0_201]
	at java.awt.EventQueue$4.run(EventQueue.java:733) [?:1.8.0_201]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) [?:1.8.0_201]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) [?:1.8.0_201]
	at java.awt.Dialog.show(Dialog.java:1084) [?:1.8.0_201]
	at javax.swing.JFileChooser.showDialog(JFileChooser.java:758) [?:1.8.0_201]
	at javax.swing.JFileChooser.showOpenDialog(JFileChooser.java:656) [?:1.8.0_201]
	at org.apache.jmeter.gui.HtmlReportUI.showFileChooser(HtmlReportUI.java:283) [ApacheJMeter_core.jar:5.3.1-SNAPSHOT]
	at org.apache.jmeter.gui.HtmlReportUI.actionPerformed(HtmlReportUI.java:229) [ApacheJMeter_core.jar:5.3.1-SNAPSHOT]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_201]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_201]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_201]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_201]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_201]
	at java.awt.Component.processMouseEvent(Component.java:6539) [?:1.8.0_201]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_201]
	at java.awt.Component.processEvent(Component.java:6304) [?:1.8.0_201]
	at java.awt.Container.processEvent(Container.java:2239) [?:1.8.0_201]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_201]
	at java.awt.Container.dispatchEventImpl(Container.java:2297) [?:1.8.0_201]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_201]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) [?:1.8.0_201]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535) [?:1.8.0_201]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) [?:1.8.0_201]
	at java.awt.Container.dispatchEventImpl(Container.java:2283) [?:1.8.0_201]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_201]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) [?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) [?:1.8.0_201]
	at java.awt.EventQueue$4.run(EventQueue.java:733) [?:1.8.0_201]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_201]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_201]

````
**Screenshots**

<img width="758" alt="Screen Shot 2020-07-25 at 15 11 35" src="https://user-images.githubusercontent.com/3127467/88457752-44e63380-ce89-11ea-97ee-e04b53bdd919.png">

**Additional Information:**
 - OS: macOS
 - OS Version: 10.11.6
- Darklaf Version: 2.4.1

**Comment by weisJ** [comment]
Addressed in ddf67db9df5fe54294f8aacc163b10723dd9d41c

**Comment by pmouawad** [comment]
Hello @weisJ ,
I confirm issue is fixed.

Regards

**Comment by pmouawad** [comment]
Hello,
But there is still an issue with File browser, see:
https://github.com/weisJ/darklaf/issues/199

Regards
