### ISSUE TITLE
Antialiasing problems on Linux

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#231]
**Describe the bug**
Some custom components are not looking good on Linux. Haven't tested them on Windows, but I assume they'd look normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/24767548/107872138-49674d80-6ea8-11eb-9718-20b78363dadb.png)

**Additional Information:**
 - OS: Manjaro Linux KDE
- Darklaf Version: 2.5.5
 

**Additional context**
- _JAVA_OPTIONS: -Dswing.aatext=TRUE -Dawt.useSystemAAFontSettings=on

**Comment by GraxCode** [comment]
Also happens on JPasswordFields with a view button.

**Comment by weisJ** [comment]
I made some changes to address this.
Relating the blurry icons: c2f93043bff7db3da9fccc6cb88bd07afe01cb08, bd87d6e84e6b765e69e6e2fa6057c70954c8ae4e 
Relating incorrect line number layout: a52cb110cec7ac79099fc641f36e22e994704a9b

I hope this resolves the issue.

**Comment by GraxCode** [comment]
Now doing some other weird stuff:
![image](https://user-images.githubusercontent.com/24767548/108586662-36dd9000-7350-11eb-81b3-4f7799e0e6d5.png)

**Comment by weisJ** [comment]
Looks like the icons are painted with a funky aspect ratio. I have added some logging to icon loading/painting process. Could you please run with the log level set to fine (`LafManager.setLevel(Level.Fine)`)?

It also looks like the frame icon isn't loaded with the correct size too. This may be related but could also be caused by a separate issue.

**Comment by weisJ** [comment]
@GraxCode I thing the last addition should fix the icon rendering. Could you confirm this is the case for you?

**Comment by GraxCode** [comment]
![image](https://user-images.githubusercontent.com/24767548/109423108-96860c00-79de-11eb-84db-44a7d98a08ea.png)
A bit better, but not fully fixed

**Comment by GraxCode** [comment]
No special log output with LafManager.setLogLevel(Level.FINEST)

**Comment by weisJ** [comment]
> No special log output with LafManager.setLogLevel(Level.FINEST)

Could you try `Level.ALL`?

**Comment by GraxCode** [comment]
![image](https://user-images.githubusercontent.com/24767548/111064976-86c6f700-84b7-11eb-93a1-da2c8431bd78.png)
Looks very good now. Can be closed IMO.
