### ISSUE TITLE
[Tooltip] Shadow broken on KDE-Plasma

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#233]
> ![image](https://user-images.githubusercontent.com/24767548/109423993-15c90f00-79e2-11eb-927b-e8ff8362cd94.png)
> Manjaro Linux

@GraxCode
This looks like a slightly different problem to me. Rather than what is happening here, there seems to be a problem with the painting of the tooltip shadow. This may be caused by some weird alpha compatibility. What desktop environment are you using and does this issue occur every time?

_Originally posted by @weisJ in https://github.com/weisJ/darklaf/issues/172#issuecomment-789259715_

**Comment by GraxCode** [comment]
Still has those weird lines
![image](https://user-images.githubusercontent.com/24767548/111500232-0c5ed700-8744-11eb-9af0-7d0d5b9cf8b3.png)

**Comment by weisJ** [comment]
Is this only the first time per tooltip or for the first tooltip all together?

**Comment by GraxCode** [comment]
Pretty sure it was first time for everything. (Can't test due to: `java.lang.NoClassDefFoundError: Unable to load class com.github.weisj.darklaf.ui.text.DarkTextUI due to missing dependency com/github/weisj/swingdsl/laf/VisualPaddingProvider`)

**Comment by weisJ** [comment]
I think the `NoClassDefFoundError` should be fixed now. That is an artifact because of a separate library I am currently creating.

> Pretty sure it was first time for everything.

That is very strange. It might be related to the configuration of the tooltip window. As pretty much the same window is shared for (almost) all tooltips that could explain why it only happens when the first tooltip is displayed.

**Comment by GraxCode** [comment]
Still throws that error after cleaning, rebuilding multiple times. Do i have to delete cache or something?

**Comment by weisJ** [comment]
Oh I think this may be related to gradle not supporting transitive dependencies with `latest.integration` as their version. The problem should go away if you declare 
`com.github.weisj:swing-dsl-laf-support:latest.integration` as a dependency manually.

**Comment by GraxCode** [comment]
Doesn't fix the problem.

**Comment by GraxCode** [comment]
But I can tell you, instead of the original lines, now a black background is behind the tooltip.

**Comment by weisJ** [comment]
Interesting. I think I'll have to setup a local KDE-Plasma environment to investigate this issue.

**Comment by weisJ** [comment]
I was not able to reproduce this issue on my machine. Are you using X-Server or wayland? Also try to to disable opengl rendering in the system settings. As I am running plasma through wsl I can only test it for X-Server with XRender instead of opengl. This gives me the reason to believe it may be related to either one.

**Comment by GraxCode** [comment]
I am using KWin and X11. Issue is still happening.

**Comment by weisJ** [comment]
You can disable the shadow by setting `UIManager.put("ToolTip.paintShadow", false)`

**Comment by loerting** [comment]
![2023-06-09-121758_1920x1080_scrot](https://github.com/weisJ/darklaf/assets/92826338/ae2fd2be-30ba-4c58-bf5e-33047924fe9d) This is what tooltips look on Manjaro i3. The shadow is rendered by i3, it doesn't know the real size of the tooltip.
