### ISSUE TITLE
Wrong background colour for tooltip text

### ISSUE THREAD

**Issue by Xujiayao** [weisJ/darklaf#298]
**Describe the bug**

- Latest Integration
- Darcula Theme
- Wrong background colour
- Different pop-up positions (not sure if this is intentional)

**To Reproduce**

Main.java
```java
package test;

import com.github.weisj.darklaf.LafManager;
import com.github.weisj.darklaf.theme.DarculaTheme;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.util.Locale;

public class Main {

	public static void main(String[] args) {
		LafManager.install(new DarculaTheme());
		Locale.setDefault(Locale.ENGLISH);

		JFrame frame = new JFrame("Darklaf - A themeable LaF for Swing");
		frame.setSize(600, 400);

		JButton button = new JButton("Click here!");

		JPanel content = new JPanel();
		content.add(button);

		frame.setLocationRelativeTo(null);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setContentPane(content);
		frame.setVisible(true);

		button.addActionListener(e -> {
			JFileChooser fileChooser = new JFileChooser();
			fileChooser.showOpenDialog(frame);
		});
	}
}
```

build.gradle

```groovy
plugins {
    id 'application'
    id 'org.beryx.jlink' version '2.24.4'
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}

application {
    //mainModule = 'Test'
    mainClass = 'test.Main'
}

dependencies {
    implementation 'com.github.weisj:darklaf-core:latest.integration'
}

jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'Test'
    }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/58985541/148330584-d0560983-85ec-4dda-9641-e5f698723700.png)

**Additional Information:**

- OS: Windows 11
- OS Version: 21H2 (22000.376)
- Darklaf Version: `latest.integration`

**Additional context**

No problem with `2.7.3`

![image](https://user-images.githubusercontent.com/58985541/148330268-ef4b0c89-0273-4596-806d-af4718aa5001.png)

**Comment by weisJ** [comment]
Thank you for reporting the issue :) Both, incorrect background and alignment, should be fixed with the latest snapshot.

**Comment by Xujiayao** [comment]
Thanks! I just tested it, the incorrect background is fixed, but the pop-up position of `Cancel` button (only `Cancel` button) is still incorrect?

![image](https://user-images.githubusercontent.com/58985541/148491752-be6862a7-d418-43ce-8c54-5834244e6ed3.png)

**Comment by Xujiayao** [comment]
Furthermore, I still have some problems with Darklaf `latest.integration`, but I'm not sure if they are bugs. Maybe I'm just not using them correctly.

If these are bugs, please tell me and I will submit another issue(s).

Main.java

```java
package test;

import com.github.weisj.darklaf.LafManager;
import com.github.weisj.darklaf.theme.DarculaTheme;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Locale;

public class Main {

	public static void main(String[] args) {
		LafManager.install(new DarculaTheme());
		Locale.setDefault(Locale.ENGLISH);

		JFrame frame = new JFrame("Darklaf - A themeable LaF for Swing");
		frame.setSize(600, 400);

		JButton button = new JButton("Click here!");

		JPanel content = new JPanel();
		content.add(button);

		frame.setLocationRelativeTo(null);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setContentPane(content);
		frame.setVisible(true);

		button.addActionListener(e -> {
			JFileChooser fileChooser = new JFileChooser();
			fileChooser.showOpenDialog(frame);
			JOptionPane.showMessageDialog(frame, "Hello World", "Test", JOptionPane.INFORMATION_MESSAGE);
		});
	}
}
```

- No window style (like undecorated)
  - No problem with `2.7.3`

![image](https://user-images.githubusercontent.com/58985541/148496120-469510b0-0f8a-4cd4-bef6-7cc8c89d9e05.png)

![image](https://user-images.githubusercontent.com/58985541/148496123-74e9466b-6863-4248-93fb-b90396d98c9b.png)

- Missing words (this seems to be related to #289)
  - Only when using Java 9+ Module

module-info.java

```java
module Test {
	requires darklaf.core;
}
```

![image](https://user-images.githubusercontent.com/58985541/148496661-e0974fa2-ac9b-442c-bcba-3b955c14d1ee.png)

![image](https://user-images.githubusercontent.com/58985541/148496717-95daa2f3-e4be-477e-88b4-09a7363737f1.png)

**Comment by weisJ** [comment]
Both are certainly not the intended behaviour

**Comment by Xujiayao** [comment]
Ok, then I'll just submit an issue for the first problem. What about this? https://github.com/weisJ/darklaf/issues/298#issuecomment-1007133859

**Comment by weisJ** [comment]
The latest snapshot should properly fix the misaligned tooltip.

**Comment by Xujiayao** [comment]
Just tested and it's fixed. Thank you so much!

**Comment by Xujiayao** [comment]
@weisJ Just found out that the console prints `----` every time it shows a tooltip. It should be because of this line added in commit 3e6672ca9b3164919b433d5c3e8176b7d8e3d678:

https://github.com/weisJ/darklaf/blob/3e6672ca9b3164919b433d5c3e8176b7d8e3d678/core/src/main/java/com/github/weisj/darklaf/ui/tooltip/ToolTipUtil.java#L142

**Comment by weisJ** [comment]
Indeed. Fixed with new snapshot
