### ISSUE TITLE
NPE in DarkComboBoxUI.getBorderInsets

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#67]
It seems to be a regression since 6e2676556fe92586157e5af090e7a0f6f40272bf

```java
        if (comboBox.getComponentOrientation().isLeftToRight()) {
            return new InsetsUIResource(boxPadding.top, boxPadding.left, boxPadding.bottom, borderSize); // <-- HERE
```

```
java.lang.NullPointerException: null
	at com.github.weisj.darklaf.ui.combobox.DarkComboBoxUI.getBorderInsets(DarkComboBoxUI.java:398) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at javax.swing.JComponent.setBorder(JComponent.java:1799) ~[?:1.8.0_222]
	at com.github.weisj.darklaf.ui.combobox.DarkComboBoxUI.installUI(DarkComboBoxUI.java:77) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at javax.swing.JComponent.setUI(JComponent.java:666) ~[?:1.8.0_222]
	at javax.swing.JComboBox.setUI(JComboBox.java:257) ~[?:1.8.0_222]
	at javax.swing.JComboBox.updateUI(JComboBox.java:266) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1238) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1229) ~[?:1.8.0_222]
	at com.github.weisj.darklaf.LafManager.updateLafRecursively(LafManager.java:194) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at com.github.weisj.darklaf.LafManager.updateLafRecursively(LafManager.java:192) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at com.github.weisj.darklaf.LafManager.updateLaf(LafManager.java:186) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at com.github.weisj.darklaf.LafManager.install(LafManager.java:172) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at com.github.weisj.darklaf.LafManager.installTheme(LafManager.java:140) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.LookAndFeelCommand.activateLookAndFeel(LookAndFeelCommand.java:204) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.LookAndFeelCommand.doAction(LookAndFeelCommand.java:225) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_222]
```

**Comment by vlsi** [comment]
The fix is to replace `comboBox` with `c` (argument)

**Comment by weisJ** [comment]
Should be fixed now

**Comment by vlsi** [comment]
Not yet fixed.
I suggest to move `comboBox.setBorder(this);` to the very end of `DarkComboBoxUI` constructor.

That is initialize all the fields first, and then call `setBorder`.

**Comment by weisJ** [comment]
Yes good catch.

**Comment by vlsi** [comment]
This is fixed now.
